# Airbnb Config: https://www.npmjs.com/package/eslint-config-airbnb
# Airbnb Config for Typescript: https://www.npmjs.com/package/eslint-config-airbnb-typescript
extends:
  - airbnb
  - airbnb-typescript
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true
  warnOnUnsupportedTypeScriptVersion: true
  project: './tsconfig.json'
env:
  browser: true
plugins:
  - testing-library
  - '@typescript-eslint'
rules:
  # This rule has been deprecated, see https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/label-has-for.md
  jsx-a11y/label-has-for: 'off'
  # When using methods with underscores inside a class, you need to enable this rule
  no-underscore-dangle:
    - error
    - allowAfterThis: true
  # We prefer not enforcing this. It's not generally a good idea to
  # name files containing JSX with a non-official extension.
  react/jsx-filename-extension: 'off'
  linebreak-style: 0
  # Sometimes it's more convenient to have named exports even
  # though only one thing has to be exported.
  import/prefer-default-export: 'off'
  # Destructuring sometimes makes code harder to read.
  react/destructuring-assignment: 'off'
  # For Typescript this is needed since it can call out false negatives.
  # https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-use-before-define.md#how-to-use
  # https://github.com/typescript-eslint/typescript-eslint/issues/2540#issuecomment-692505191
  no-use-before-define: 'off'
  react/function-component-definition:
    - error
    - namedComponents: arrow-function
      unnamedComponents: arrow-function
  react/react-in-jsx-scope: 'off'
  react/prop-types: 'off'
  react/require-default-props: 'off'
  react/jsx-props-no-spreading: 'off'
  react/button-has-type: 'off'
  '@typescript-eslint/type-annotation-spacing': error
# Allows for absolute imports
settings:
  import/resolver:
    node:
      paths: ["src"]
