x-common:
  &common
  image: 'node:16.5.0'
  environment:
    - REACT_APP_API_BASE_URL=http://dummy-server

pipeline:
  setup:
    <<: *common
    commands:
      - npm ci --prefer-offline
  js-lint:
    <<: *common
    group: fe-build
    commands:
      - CI=true npm run lint
  js-test:
    <<: *common
    group: fe-build
    commands:
      - CI=true npm run test
  js-try-cra:
    <<: *common
    group: fe-build
    commands:
      - CURRENT_DIR=$(pwd)
      - cd /tmp
      - npx create-react-app --template file:$CURRENT_DIR dummy-project
      - cd dummy-project
      - CI=true npm test
